### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by lonix1** [tai-q/docker-taiga#2]
What is the update procedure?

**Comment by PatrickTaibel** [comment]
Hi,

I have updated the used taiga version to 4.2.13 and pushed it to docker hub (and fixed a build error with debian buster).

About the procedure: Change the environment variables in the Dockerfile to the current version and build the docker image (or write an issue and I will update it myself 😄). Check afterwards if anything breaks using this procedure (might happen for major releases).

Regards,
Patrick
